### ISSUE TITLE
signup form, error redirect Yelp Camp title. 

### ISSUE THREAD

**Issue by BorisVV** [BorisVV/OnlineStoreProject#20]

**Comment by BorisVV** [comment]
When the user's password doesn't match and the form reloads, the title is displaying the Yelp Camp title.
:)

**Comment by momojohnson** [comment]
Like me take a look at this right now

**Comment by momojohnson** [comment]
I have fixed the title error. Mistakenly included Yelp Camp in the title of the base template.
